# Permalinks
permalink:           pretty

# Setup
title:               Technically Wrong
tagline:             On being a novice coder
url:                 https://aleschreiber.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :expanded # You might prefer to minify using :compressed

# About/contact
author:
  name:              Alessio Schreiber
  url:               http://alessioschreiber.me/
  email:             alessio.schreiber@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Use the following plug-ins
gems:
  - jekyll-paginate # Pagination Generator for Jekyll 
  - jekyll-gist # Liquid tag for displaying GitHub Gists in Jekyll sites

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
